name: build

on: 
  - push
  - workflow_dispatch

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
          cache: npm
      - run: npm install

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
          cache: npm
      - run: npm install
      - run: npm run lint

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
          cache: npm
      - run: npm install
      - run: npm run build:tracker
      - run: npm run build:router
      - run: npm run test:ci
      - uses: actions/upload-artifact@v2
        with:
          name: tests-coverage
          path: coverage/
          if-no-files-found: error
      - uses: coverallsapp/github-action@1.1.3
        with:
          path-to-lcov: ./coverage/tracker/lcov.info
          parallel: true
          flag-name: tracker
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: coverallsapp/github-action@1.1.3
        with:
          path-to-lcov: ./coverage/router/lcov.info
          parallel: true
          flag-name: router
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: coverallsapp/github-action@1.1.3
        with:
          parallel-finished: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: [lint, test]
    runs-on: ubuntu-latest
    env:
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      GPG_SECRET_KEY: ${{ secrets.GPG_SECRET_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.13.2
          cache: npm
      - run: echo -n "${GPG_SECRET_KEY}" > git_gpg_key.asc
      - run: gpg --batch --yes --import git_gpg_key.asc
      - run: git config commit.gpgsign true
      - run: git config --global user.signingkey ${GPG_KEY_ID}
      - run: npm install
      - run: npm run build:prod:tracker
      - run: npm run build:prod:router
      - uses: actions/upload-artifact@v2
        with:
          name: dist-prod
          path: dist-prod
          if-no-files-found: error
      - run: npm run semantic-release:ci
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GIT_COMMITTER_NAME }}
